APP_TITLE = "Inventory Management System"

LOGIN_TITLE = "Acesso ao Sistema"
LOGIN_BUTTON = "ENTRAR"
LOGIN_FORGOT = "Esqueceu a Senha?"
LOGIN_REQUIRED = "Email e Senha são obrigatórios."
LOGIN_INVALID = "Credenciais inválidas. Tente novamente."

SECTION_HOME = "Início"
SECTION_COMPANY = "Empresas"
SECTION_ROLE = "Funções"
SECTION_USER = "Usuários"
SECTION_LOCATION = "Locais"
SECTION_PRODUCT = "Produtos"
SECTION_CONFIG = "Configurações"

PAGE_HOME_TITLE = "Página Inicial"
PAGE_HOME_SUBTITLE = "Bem-vindo ao IMS!"

CONFIG_TITLE = "⚙️ Configurações"
CONFIG_SUBTITLE = "Preferências e ajustes do sistema."

COMPANY_TITLE = "Empresas"
COMPANY_ADD = "Adicionar Empresa"
COMPANY_ADD_TITLE = "Adicionar Nova Empresa"
COMPANY_EDIT_TITLE = "Editar Empresa"

ROLE_TITLE = "Funções"
ROLE_ADD = "Adicionar Função"
ROLE_ADD_TITLE = "Adicionar Nova Função"
ROLE_EDIT_TITLE = "Editar Função"

USER_TITLE = "Usuários"
USER_ADD = "Adicionar Usuário"
USER_ADD_TITLE = "Adicionar Novo Usuário"
USER_EDIT_TITLE = "Editar Usuário"

LOCATION_TITLE = "Locais"
LOCATION_ADD = "Adicionar Local"
LOCATION_ADD_TITLE = "Adicionar Novo Local"
LOCATION_EDIT_TITLE = "Editar Local"

PRODUCT_TITLE = "Produtos"
PRODUCT_ADD = "Adicionar Produto"
PRODUCT_ADD_TITLE = "Adicionar Novo Produto"
PRODUCT_EDIT_TITLE = "Editar Produto"

FIELD_NAME = "Nome"
FIELD_NIF = "NIF (Opcional)"
FIELD_EMAIL = "Email"
FIELD_PASSWORD = "Senha"
FIELD_ROLE = "Função"
FIELD_COMPANY = "Empresa"
FIELD_ACTIVE = "Ativo"
FIELD_SKU = "SKU"
FIELD_BARCODE = "Barcode"
FIELD_PRICE = "Preço"
FIELD_UNIT = "Unidade"

HINT_COMPANY_NAME = "Digite o nome da empresa"
HINT_NIF = "Digite o NIF"
HINT_ROLE_NAME = "Digite o nome da função"
HINT_USER_EMAIL = "Digite o email"
HINT_USER_PASSWORD = "Digite a senha"
HINT_LOCATION_NAME = "Digite o nome do local"
HINT_PRODUCT_SKU = "Digite o SKU"
HINT_PRODUCT_BARCODE = "Digite o barcode"
HINT_PRODUCT_NAME = "Digite o nome"
HINT_PRICE = "0.00"
HINT_UNIT = "UN"

ERROR_REQUIRED_NAME = "O nome é obrigatório"
ERROR_INVALID_PRICE = "Preço inválido"

BTN_CANCEL = "Cancelar"
BTN_CREATE = "Criar"
BTN_SAVE = "Salvar"
